"""Domain model for tasks generated by the LLM."""

from dataclasses import dataclass

from pydantic import BaseModel


@dataclass
class GeneratedTask(BaseModel):
    """Represents a task generated from a meeting summary.

    Attributes:
        task_name: Name/title of the task.
        task_description: Detailed task description.
        task_assigne: Assignee name(s) as a string.
        task_status: Target status for the task.
        task_priority: Target priority for the task.
        folder: Target folder name.
    """
    task_name: str
    task_description: str
    task_assigne: str
    task_status: str
    task_priority: str
    folder: str